import mysql.connector,sys
from datetime import date

con = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="root",
  database="mycart"
)

c = con.cursor()

print('MyCart Application\n-------------------')
ch=str(sys.argv[1])


def admin_add_product():
    while True:
        print('\nAdd Product Details\n')
        pname=input('Enter Product Name :')
        category=input('Enter Product Category :')
        price=input('Enter Product Price :')
        c.execute("insert into product values('"+pname+"','"+category+"','"+price+"')")
        con.commit()
        print(pname,'Inserted Successfully.')
        yn=input("Do You Want To Add New Product (yes/no) :")
        if yn != 'yes':
            break

def admin_product_details():
    print('----------------------------------------------------')
    print('\n\tDetails Of Product Added to Cart By User')
    print('----------------------------------------------------\n')
    c.execute("select cart.*,product.price from cart,product where product.prodname=cart.prodname")
    cart_details=c.fetchall()
    for i in cart_details:
        print('\n\tUser Name :',i[1],'\n\tProduct Name :',i[0],'\n\tPrice :',i[3],'\n\tDate :',i[2])
    print('----------------------------------------------------')

def admin_see_all_bill():
    print('----------------------------------------------------')
    print('\nBill Generated By Users')
    print('----------------------------------------------------')
    c.execute("select distinct username from bill")
    users=c.fetchall()
    for i in users:
        username=i[0]
        c.execute("select * from bill where username='"+username+"'")
        record=c.fetchall()
        date1=date.today()
        total_price=0
        print('\n-------------------------------------------------------------------------')
        print('\t\t\tYour Bill')
        print('\n\tUser Name : '+username+'\n-------------------------------------------------------------------------\n\n')
        for i in record:
            print('\tProduct :',i[0],'\tPrice :',i[2],'\tDate Of Cart:',i[3])
            total_price+=i[2]
        discount=0
        if total_price > 10000:
            discount=500
        final_amt=total_price-discount
        print('\n\tActual Total Amount :',total_price)
        print('\tDiscount Amount :',discount)
        print('\tFinal Bill Amount :',final_amt)
        print('\n-------------------------------------------------------------------------')

    print('----------------------------------------------------')

def user_categories():
    c.execute('select distinct category from product')
    cat = c.fetchall()
    d ={}
    j=1
    for i in cat:
        d[j]=i[0]
        print('\t',j,':',d[j])
        j+=1
    print('\tSelect Category (',end='')
    for i in range(1,j-1):
        print(str(i)+'/',end='')

    print(str(j-1)+') : ',end='')

    ch1 = int(input())
    if ch1 >= j:
        print('Wrong Category.')
                        
    else:
        c.execute("select prodname from product where category='"+d[ch1]+"'")
        print('\nAll Product Of',d[ch1],'Category:')
        p=c.fetchall()
        d ={}
        j=1
        for i in p:
            d[j]=i[0]
            print('\t',j,':',d[j])
            j+=1

        print('\tSelect Product (',end='')
        for i in range(1,j-1):
            print(str(i)+'/',end='')
        print(str(j-1)+') : ',end='')
        ch2=int(input())
        if ch2 >= j:
            print('Wrong Product Selected.')
        else:
            c.execute("select * from product where prodname='"+d[ch2]+"'")
            print('\n',d[ch2].capitalize(),'Details :')
            prod=c.fetchall()
            for i in prod:
                print('\tProduct Name :',i[0].title())
                print('\tProduct Category :',i[1].title())
                print('\tProduct Price :',i[2])

def user_see_all_product(username):
    print('\n\nList Of All Product :\n')
    c.execute('select * from product')
    p=c.fetchall()
    d={}
    j=1
    print('--------------------------------------------\nId\tProduct Name\tCategory\tPrice\n--------------------------------------------')
    for i in p:
        print(str(j)+'\t'+str(i[0])+'\t\t'+str(i[1])+'\t\t'+str(i[2]))
        d[j]=i[0]
        j+=1
    print('--------------------------------------------')
    pid=int(input('\nSelect Product Id to Add To Cart : '))
    if pid>=j:
        print('You Selected Wrong Product Id.')
    else:
        date1=date.today()
        c.execute("insert into cart values('"+d[pid]+"','"+username+"','"+str(date1)+"')")
        con.commit()
        print(d[pid],'Addded To Cart...')
                    
def user_cart_detail_buy_prod(username):
    while True:
        print('\n\nYour Cart Details : \n')
        c.execute("select product.*,cart.date from product,cart where product.prodname=cart.prodname and username='"+username+"'")
        carts=c.fetchall()
        d={}
        j=1
        for i in carts:
            d[j]=i[0]
            print('\nProduct No :',j)
            print('\tProduct Name :',i[0],'\n\tCategory :',i[1],'\n\tPrice :',i[2],'\n\tDate :',i[3])
            j+=1
        buy=input('\nDo You Want To Buy Any Product (yes/no):')
        if buy == 'yes':
            print('\nSelect Product Id To Buy Product (',end='')
            for i in range(1,j-1):
                print(str(i)+'/',end='')
            print(str(j-1)+') : ',end='')
            pid=int(input())
                            
            if pid>=j or j == 1 or pid<=0:
                print('You Selected Wrong Product Id.')
            
            else:
                date1=date.today()
                c.execute("select price from product where prodname='"+d[pid]+"'")
                data=c.fetchall()
                price=data[0][0]
                                    
                c.execute("insert into bill values('"+d[pid]+"','"+username+"','"+str(price)+"','"+str(date1)+"')")
                con.commit()
                c.execute("delete from cart where username='"+username+"' and prodname='"+d[pid]+"'")
                con.commit()
                print('\n\tYou Buy',d[pid])
                yn=input('Do You Want Buy New Product (yes/no) :')
                if yn!='yes':
                    break
        yn=input('Do You Want To Continue in Card Details (yes/no) :')
        if yn!='yes':
            break
                        
def user_remove_cart_prod(username):
    while True:
        print('\n\nYour Cart Details : \n')
        c.execute("select product.*,cart.date from product,cart where product.prodname=cart.prodname and username='"+username+"'")
        carts=c.fetchall()
        d={}
        j=1
        for i in carts:
            d[j]=i[0]
            print('\nProduct No :',j)
            print('\tProduct Name :',i[0],'\n\tCategory :',i[1],'\n\tPrice :',i[2],'\n\tDate :',i[3])
            j+=1

        if j!=1:
            print('\nSelect Product Id To Remove From Cart (',end='')
            for i in range(1,j-1):
                print(str(i)+'/',end='')
            print(str(j-1)+') : ',end='')
            pid=int(input())
            if pid>=j or j==1 or pid<=0:
                print('You Selected Wrong Product Id.')
            else:
                c.execute("delete from cart where username='"+username+"' and prodname='"+d[pid]+"'")
                con.commit()
                print(d[pid],'is Removed From Cart.')
            yn=input('Do You Want To Remove Another Product (yes/no) :')
            if yn!='yes':
                break
        yn=input('Do You Want To Continue in Remove Cart (yes/no) :')
        if yn!='yes':
            break

def user_bill(username):
    c.execute("select * from bill where username='"+username+"'")
    record=c.fetchall()
    date1=date.today()
    total_price=0
    print('\n-------------------------------------------------------------------------')
    print('\t\t\tYour Bill')
    print('\n\tUser Name : '+username+'\n-------------------------------------------------------------------------\n\n')
    for i in record:
        print('\tProduct :',i[0],'\tPrice :',i[2],'\tDate Of Cart:',i[3])
        total_price+=i[2]
    discount=0
    if total_price > 10000:
        discount=500
    final_amt=total_price-discount
    print('\n\tActual Total Amount :',total_price)
    print('\tDiscount Amount :',discount)
    print('\tFinal Bill Amount :',final_amt)
    print('\n-------------------------------------------------------------------------')

def user_register():
    print('\n\n\nNew User Registration Process\n\n')
    name=str(input('Enter User Name : '))
    address=str(input('Enter Address : '))
    mobile=str(input('Enter Mobile No : '))
    password1=str(input('Enter Password : '))
    password2=str(input('Re-Enter Password : '))
            
    if password1 == password2:
        k=c.execute("insert into user values('"+name+"','"+address+"','"+mobile+"','"+password1+"')")
        con.commit()
        print('Successfully Registred')
        

    else:
        print('Both Passwords Must Be Same.')


    
if ch == 'admin':
    while True:
        print('You Are Admin..\n    \tPlease Login')
        admin=input('\nEnter Admin Name : ')
        password=input('Enter Password : ')
        if admin == 'admin' and password == 'admin123':
            while True:
                print('\n1 : Add Product And Category\n2 : Details Of Product Added To Cart By User\n3 : Bill Generated By All User\nSelect Option (1/2/3) :',end='')
                choice=int(input())
                if choice == 1:
                    admin_add_product()
                elif choice == 2:
                    admin_product_details()
                elif choice == 3:
                    admin_see_all_bill()
                else:
                    print('\nYou Have Selected Wrong Option.')
                    break
            yn=input("\nDo You Want To Continue In Admin View (yes/no) :")
            if yn != 'yes':
                break
            
        else:
            print('Incorrect Admin or Password.')
            yn=input('Do You Want To Login Again (yes/no) : ')
            if yn != 'yes':
                break
        
        
elif ch == 'user':
    while True:
        print('\nYou Are User..')
        print('1 : Login\n2 : Registeration for new User\n3 : Exit')
        print('\nSelect Option (1/2/3) : ',end='')
        choice=int(input())
        if choice == 1:
            username=str(input('Enter Username : '))
            password=str(input('Enter Password : '))

            c.execute("select username from user where username='"+username+"' and password='"+password+"'")
            user=c.fetchall()
            while user:
                print('\n1 : Categories\n2 : Add Product To Cart\n3 : Your Cart Details And Buy Product\n4 : Remove Product From Cart \n5 : Your Bill\nSelect Any Option(1/2/3/4/5) : ',end='')
                
                ch0=int(input())
                    
                if ch0 == 1:
                    user_categories()
                elif ch0 == 2:
                    user_see_all_product(username)
                elif ch0 == 3:
                    user_cart_detail_buy_prod(username)             
                elif ch0 == 4:
                    user_remove_cart_prod(username) 
                elif ch0 == 5:
                    user_bill(username)
                else:
                    print('Wrong Input By User...')
                yn=input('\nDo You Want to Continue in User Profile (yes/no) : ')
                if yn!='yes':
                    break

            else:
                print("Wrong Username Or Password..")

        elif choice == 2:
            user_register()
            yn=input('Continue On User View (yes/no) :')
            if yn != 'yes':
                break
        elif choice==3:
            print('You Pressed Exit Option !!')
            break

        else:
            print('You Have Entered Wrong Choice !!\nPlease Choose Correct Option.')         
            
else:
    print('You Have Entered Wrong Input.')


